{\rtf1\ansi\ansicpg1252\cocoartf1561\cocoasubrtf600
{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0  'created_at': datetime.datetime(2018, 12, 10, 22, 8, 32, 501279, tzinfo=<UTC>),\
 'updated_at': datetime.datetime(2018, 12, 10, 22, 19, 58, 882873, tzinfo=<UTC>)\}\
\
In [9]: author = Author.objects.get(id = 4)\
\
In [10]: author\
Out[10]: <Author: Author object>\
\
In [11]: author.__dict__\
Out[11]:\
\{'_state': <django.db.models.base.ModelState at 0x10752aac8>,\
 'id': 4,\
 'first_name': 'William',\
 'last_name': ' Shakespeare',\
 'email': 'william@book.com',\
 'notes': 'no value',\
 'created_at': datetime.datetime(2018, 12, 10, 22, 15, 1, 27856, tzinfo=<UTC>),\
 'updated_at': datetime.datetime(2018, 12, 10, 22, 15, 1, 27928, tzinfo=<UTC>)\}\
\
In [12]: author.name = Bill\
---------------------------------------------------------------------------\
NameError                                 Traceback (most recent call last)\
<ipython-input-12-86449403a78b> in <module>\
----> 1 author.name = Bill\
\
NameError: name 'Bill' is not defined\
\
In [13]: author.first_name = Bill\
---------------------------------------------------------------------------\
NameError                                 Traceback (most recent call last)\
<ipython-input-13-8679c24e55d8> in <module>\
----> 1 author.first_name = Bill\
\
NameError: name 'Bill' is not defined\
\
In [14]: author.first_name = "Bill"\
\
In [15]: author\
Out[15]: <Author: Author object>\
\
In [16]: auhtor.__dict__\
---------------------------------------------------------------------------\
NameError                                 Traceback (most recent call last)\
<ipython-input-16-f2cce123c5df> in <module>\
----> 1 auhtor.__dict__\
\
NameError: name 'auhtor' is not defined\
\
In [17]: author.__dict__\
Out[17]:\
\{'_state': <django.db.models.base.ModelState at 0x10752aac8>,\
 'id': 4,\
 'first_name': 'Bill',\
 'last_name': ' Shakespeare',\
 'email': 'william@book.com',\
 'notes': 'no value',\
 'created_at': datetime.datetime(2018, 12, 10, 22, 15, 1, 27856, tzinfo=<UTC>),\
 'updated_at': datetime.datetime(2018, 12, 10, 22, 15, 1, 27928, tzinfo=<UTC>)\}\
\
In [18]: author = Author.objects.get(id = 2)\
\
In [19]: author.__dict__\
Out[19]:\
\{'_state': <django.db.models.base.ModelState at 0x1075d78d0>,\
 'id': 2,\
 'first_name': 'Emily',\
 'last_name': 'Dickinson',\
 'email': 'emily@book.com',\
 'notes': 'no value',\
 'created_at': datetime.datetime(2018, 12, 10, 22, 12, 45, 698866, tzinfo=<UTC>),\
 'updated_at': datetime.datetime(2018, 12, 10, 22, 12, 45, 698909, tzinfo=<UTC>)\}\
\
In [20]: book1 = Book.objects.get(id = 1)\
\
In [21]: book1.__dict__\
Out[21]:\
\{'_state': <django.db.models.base.ModelState at 0x107664fd0>,\
 'id': 1,\
 'name': 'C #',\
 'desc': 'terrible book',\
 'created_at': datetime.datetime(2018, 12, 10, 22, 8, 32, 501279, tzinfo=<UTC>),\
 'updated_at': datetime.datetime(2018, 12, 10, 22, 19, 58, 882873, tzinfo=<UTC>)\}\
\
In [22]: book2 = Book.objects.get(id = 2)\
\
In [23]: book3 = Book.objects.get(id = 2)\
\
In [24]: book2 = Book.objects.get(id = 2)\
\
In [25]: book3 = book2 = Book.objects.get(id = 3)\
\
In [26]: book2.__dict__\
Out[26]:\
\{'_state': <django.db.models.base.ModelState at 0x1076adb00>,\
 'id': 3,\
 'name': 'Python',\
 'desc': 'great book',\
 'created_at': datetime.datetime(2018, 12, 10, 22, 9, 25, 248595, tzinfo=<UTC>),\
 'updated_at': datetime.datetime(2018, 12, 10, 22, 9, 25, 248663, tzinfo=<UTC>)\}\
\
In [27]: book3.__dict__\
Out[27]:\
\{'_state': <django.db.models.base.ModelState at 0x1076adb00>,\
 'id': 3,\
 'name': 'Python',\
 'desc': 'great book',\
 'created_at': datetime.datetime(2018, 12, 10, 22, 9, 25, 248595, tzinfo=<UTC>),\
 'updated_at': datetime.datetime(2018, 12, 10, 22, 9, 25, 248663, tzinfo=<UTC>)\}\
\
In [28]: book2 = Author.objects.get(id = 2)\
\
In [29]: book2.__dict__\
Out[29]:\
\{'_state': <django.db.models.base.ModelState at 0x1076ad2e8>,\
 'id': 2,\
 'first_name': 'Emily',\
 'last_name': 'Dickinson',\
 'email': 'emily@book.com',\
 'notes': 'no value',\
 'created_at': datetime.datetime(2018, 12, 10, 22, 12, 45, 698866, tzinfo=<UTC>),\
 'updated_at': datetime.datetime(2018, 12, 10, 22, 12, 45, 698909, tzinfo=<UTC>)\}\
\
In [30]: book2 = Book.objects.get(id = 2)\
\
In [31]: book2.__dict__\
Out[31]:\
\{'_state': <django.db.models.base.ModelState at 0x1077426a0>,\
 'id': 2,\
 'name': 'Java',\
 'desc': 'good book',\
 'created_at': datetime.datetime(2018, 12, 10, 22, 8, 56, 376415, tzinfo=<UTC>),\
 'updated_at': datetime.datetime(2018, 12, 10, 22, 8, 56, 376482, tzinfo=<UTC>)\}\
\
In [32]: author.author.add(book1,book2,book3)\
\
In [33]: author\
Out[33]: <Author: Author object>\
\
In [34]: author.__dict__\
Out[34]:\
\{'_state': <django.db.models.base.ModelState at 0x1075d78d0>,\
 'id': 2,\
 'first_name': 'Emily',\
 'last_name': 'Dickinson',\
 'email': 'emily@book.com',\
 'notes': 'no value',\
 'created_at': datetime.datetime(2018, 12, 10, 22, 12, 45, 698866, tzinfo=<UTC>),\
 'updated_at': datetime.datetime(2018, 12, 10, 22, 12, 45, 698909, tzinfo=<UTC>)\}\
\
In [35]: first_author = Author.objects.get(id = 2)\
\
In [36]: exit()\
(djangoPy3Env) Chis-MacBook-Air:Author_Book chinguyen$ python manage.py makemigrations\
Did you rename author.author to author.books (a ManyToManyField)? [y/N] Y\
Migrations for 'book_app':\
  apps/book_app/migrations/0003_auto_20181210_2235.py:\
    - Rename field author on author to books\
(djangoPy3Env) Chis-MacBook-Air:Author_Book chinguyen$ python manage.py migrat\
Unknown command: 'migrat'\
Type 'manage.py help' for usage.\
(djangoPy3Env) Chis-MacBook-Air:Author_Book chinguyen$ python manage.py migrate\
Operations to perform:\
  Apply all migrations: admin, auth, book_app, contenttypes, sessions\
Running migrations:\
  Rendering model states... DONE\
  Applying book_app.0003_auto_20181210_2235... OK\
(djangoPy3Env) Chis-MacBook-Air:Author_Book chinguyen$ python manage.py shell\
Python 3.7.1 (default, Nov  6 2018, 18:45:35)\
Type 'copyright', 'credits' or 'license' for more information\
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.\
\
In [1]: from apps.book_app.models import *\
\
In [2]: author = Author.objects.get(id =2)\
\
In [3]: author.__dict__\
Out[3]:\
\{'_state': <django.db.models.base.ModelState at 0x10a7cf710>,\
 'id': 2,\
 'first_name': 'Emily',\
 'last_name': 'Dickinson',\
 'email': 'emily@book.com',\
 'notes': 'no value',\
 'created_at': datetime.datetime(2018, 12, 10, 22, 12, 45, 698866, tzinfo=<UTC>),\
 'updated_at': datetime.datetime(2018, 12, 10, 22, 12, 45, 698909, tzinfo=<UTC>)\}\
\
In [4]: author.books.add(1,2,3)\
\
In [5]: author.books\
Out[5]: <django.db.models.fields.related_descriptors.create_forward_many_to_many_manager.<locals>.ManyRelatedManager at 0x10a7ce7f0>\
\
In [6]: author.books.__dict__\
Out[6]:\
\{'_constructor_args': ((<Author: Author object>,), \{\}),\
 'creation_counter': 17,\
 'model': apps.book_app.models.Book,\
 'name': None,\
 '_db': None,\
 '_hints': \{\},\
 'instance': <Author: Author object>,\
 'query_field_name': 'authors',\
 'prefetch_cache_name': 'books',\
 'source_field_name': 'author',\
 'target_field_name': 'book',\
 'symmetrical': False,\
 'through': apps.book_app.models.Author_books,\
 'reverse': False,\
 'source_field': <django.db.models.fields.related.ForeignKey: author>,\
 'target_field': <django.db.models.fields.related.ForeignKey: book>,\
 'core_filters': \{'authors__id': 2\},\
 'related_val': (2,)\}\
\
In [7]: author\
Out[7]: <Author: Author object>\
\
In [8]: author.__dict__\
Out[8]:\
\{'_state': <django.db.models.base.ModelState at 0x10a7cf710>,\
 'id': 2,\
 'first_name': 'Emily',\
 'last_name': 'Dickinson',\
 'email': 'emily@book.com',\
 'notes': 'no value',\
 'created_at': datetime.datetime(2018, 12, 10, 22, 12, 45, 698866, tzinfo=<UTC>),\
 'updated_at': datetime.datetime(2018, 12, 10, 22, 12, 45, 698909, tzinfo=<UTC>)\}\
\
In [9]: author.books.all()\
Out[9]: <QuerySet [<Book: Book object>, <Book: Book object>, <Book: Book object>]>\
\
In [10]: author.books.all().values()\
Out[10]: <QuerySet [\{'id': 1, 'name': 'C #', 'desc': 'terrible book', 'created_at': datetime.datetime(2018, 12, 10, 22, 8, 32, 501279, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 19, 58, 882873, tzinfo=<UTC>)\}, \{'id': 2, 'name': 'Java', 'desc': 'good book', 'created_at': datetime.datetime(2018, 12, 10, 22, 8, 56, 376415, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 8, 56, 376482, tzinfo=<UTC>)\}, \{'id': 3, 'name': 'Python', 'desc': 'great book', 'created_at': datetime.datetime(2018, 12, 10, 22, 9, 25, 248595, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 9, 25, 248663, tzinfo=<UTC>)\}]>\
\
In [11]: first_author = Author.objects.get(1)\
---------------------------------------------------------------------------\
TypeError                                 Traceback (most recent call last)\
<ipython-input-11-2f92dd8d2888> in <module>\
----> 1 first_author = Author.objects.get(1)\
\
~/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/db/models/manager.py in manager_method(self, *args, **kwargs)\
     83         def create_method(name, method):\
     84             def manager_method(self, *args, **kwargs):\
---> 85                 return getattr(self.get_queryset(), name)(*args, **kwargs)\
     86             manager_method.__name__ = method.__name__\
     87             manager_method.__doc__ = method.__doc__\
\
~/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/db/models/query.py in get(self, *args, **kwargs)\
    374         keyword arguments.\
    375         """\
--> 376         clone = self.filter(*args, **kwargs)\
    377         if self.query.can_filter() and not self.query.distinct_fields:\
    378             clone = clone.order_by()\
\
~/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/db/models/query.py in filter(self, *args, **kwargs)\
    792         set.\
    793         """\
--> 794         return self._filter_or_exclude(False, *args, **kwargs)\
    795\
    796     def exclude(self, *args, **kwargs):\
\
~/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/db/models/query.py in _filter_or_exclude(self, negate, *args, **kwargs)\
    810             clone.query.add_q(~Q(*args, **kwargs))\
    811         else:\
--> 812             clone.query.add_q(Q(*args, **kwargs))\
    813         return clone\
    814\
\
~/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/db/models/sql/query.py in add_q(self, q_object)\
   1225         existing_inner = set(\
   1226             (a for a in self.alias_map if self.alias_map[a].join_type == INNER))\
-> 1227         clause, _ = self._add_q(q_object, self.used_aliases)\
   1228         if clause:\
   1229             self.where.add(clause, AND)\
\
~/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/db/models/sql/query.py in _add_q(self, q_object, used_aliases, branch_negated, current_negated, allow_joins, split_subq)\
   1251                     child, can_reuse=used_aliases, branch_negated=branch_negated,\
   1252                     current_negated=current_negated, connector=connector,\
-> 1253                     allow_joins=allow_joins, split_subq=split_subq,\
   1254                 )\
   1255                 joinpromoter.add_votes(needed_inner)\
\
~/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/db/models/sql/query.py in build_filter(self, filter_expr, branch_negated, current_negated, can_reuse, connector, allow_joins, split_subq)\
   1128         if isinstance(filter_expr, dict):\
   1129             raise FieldError("Cannot parse keyword query as dict")\
-> 1130         arg, value = filter_expr\
   1131         if not arg:\
   1132             raise FieldError("Cannot parse keyword query %r" % arg)\
\
TypeError: cannot unpack non-iterable int object\
\
In [12]: first_author = Author.objects.get(id = 1)\
\
In [13]: first_author.books.add(1,2)\
\
In [14]: first.author.books.all().values()\
---------------------------------------------------------------------------\
NameError                                 Traceback (most recent call last)\
<ipython-input-14-31ec279b62f7> in <module>\
----> 1 first.author.books.all().values()\
\
NameError: name 'first' is not defined\
\
In [15]: first_author.books.all().values()\
Out[15]: <QuerySet [\{'id': 1, 'name': 'C #', 'desc': 'terrible book', 'created_at': datetime.datetime(2018, 12, 10, 22, 8, 32, 501279, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 19, 58, 882873, tzinfo=<UTC>)\}, \{'id': 2, 'name': 'Java', 'desc': 'good book', 'created_at': datetime.datetime(2018, 12, 10, 22, 8, 56, 376415, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 8, 56, 376482, tzinfo=<UTC>)\}]>\
\
In [16]: third_author = Author.objects.get(id = )\
  File "<ipython-input-16-e28c0b9be433>", line 1\
    third_author = Author.objects.get(id = )\
                                           ^\
SyntaxError: invalid syntax\
\
\
In [17]: third_author = Author.objects.get(id = 3)\
\
In [18]: third_author.books.add(1,2,3,4)\
\
In [19]: third_author.books.all().values()\
Out[19]: <QuerySet [\{'id': 1, 'name': 'C #', 'desc': 'terrible book', 'created_at': datetime.datetime(2018, 12, 10, 22, 8, 32, 501279, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 19, 58, 882873, tzinfo=<UTC>)\}, \{'id': 2, 'name': 'Java', 'desc': 'good book', 'created_at': datetime.datetime(2018, 12, 10, 22, 8, 56, 376415, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 8, 56, 376482, tzinfo=<UTC>)\}, \{'id': 3, 'name': 'Python', 'desc': 'great book', 'created_at': datetime.datetime(2018, 12, 10, 22, 9, 25, 248595, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 9, 25, 248663, tzinfo=<UTC>)\}, \{'id': 4, 'name': 'PHP', 'desc': 'obsolete book', 'created_at': datetime.datetime(2018, 12, 10, 22, 9, 51, 66207, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 9, 51, 66262, tzinfo=<UTC>)\}]>\
\
In [20]: fourth_author = Author.objects.get(id = 4)\
\
In [21]: fourth_author.books.add(1,2,3,4,5)\
\
In [22]: fourth_author.books.all()\
Out[22]: <QuerySet [<Book: Book object>, <Book: Book object>, <Book: Book object>, <Book: Book object>, <Book: Book object>]>\
\
In [23]: fourth_author.books.all().values()\
Out[23]: <QuerySet [\{'id': 1, 'name': 'C #', 'desc': 'terrible book', 'created_at': datetime.datetime(2018, 12, 10, 22, 8, 32, 501279, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 19, 58, 882873, tzinfo=<UTC>)\}, \{'id': 2, 'name': 'Java', 'desc': 'good book', 'created_at': datetime.datetime(2018, 12, 10, 22, 8, 56, 376415, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 8, 56, 376482, tzinfo=<UTC>)\}, \{'id': 3, 'name': 'Python', 'desc': 'great book', 'created_at': datetime.datetime(2018, 12, 10, 22, 9, 25, 248595, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 9, 25, 248663, tzinfo=<UTC>)\}, \{'id': 4, 'name': 'PHP', 'desc': 'obsolete book', 'created_at': datetime.datetime(2018, 12, 10, 22, 9, 51, 66207, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 9, 51, 66262, tzinfo=<UTC>)\}, \{'id': 5, 'name': 'Ruby', 'desc': 'ok book', 'created_at': datetime.datetime(2018, 12, 10, 22, 10, 28, 861267, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 10, 28, 861310, tzinfo=<UTC>)\}]>\
\
In [24]: thirdbook = Book.objects.get(id = 3)\
\
In [25]: thirdbook.authors.all()\
Out[25]: <QuerySet [<Author: Author object>, <Author: Author object>, <Author: Author object>]>\
\
In [26]: thirdbook.authors.all().values()\
Out[26]: <QuerySet [\{'id': 2, 'first_name': 'Emily', 'last_name': 'Dickinson', 'email': 'emily@book.com', 'notes': 'no value', 'created_at': datetime.datetime(2018, 12, 10, 22, 12, 45, 698866, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 12, 45, 698909, tzinfo=<UTC>)\}, \{'id': 3, 'first_name': 'Fyodor', 'last_name': 'Do', 'email': 'fyodor@book.com', 'notes': 'no value', 'created_at': datetime.datetime(2018, 12, 10, 22, 13, 54, 508044, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 13, 54, 508089, tzinfo=<UTC>)\}, \{'id': 4, 'first_name': 'William', 'last_name': ' Shakespeare', 'email': 'william@book.com', 'notes': 'no value', 'created_at': datetime.datetime(2018, 12, 10, 22, 15, 1, 27856, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 15, 1, 27928, tzinfo=<UTC>)\}]>\
\
In [27]: thirdbook.authors.all().first_name\
---------------------------------------------------------------------------\
AttributeError                            Traceback (most recent call last)\
<ipython-input-27-764d962919fe> in <module>\
----> 1 thirdbook.authors.all().first_name\
\
AttributeError: 'QuerySet' object has no attribute 'first_name'\
\
In [28]: thirdbook.authors.remove(2)\
\
In [29]: thirdbook.authors.all().values()\
Out[29]: <QuerySet [\{'id': 3, 'first_name': 'Fyodor', 'last_name': 'Do', 'email': 'fyodor@book.com', 'notes': 'no value', 'created_at': datetime.datetime(2018, 12, 10, 22, 13, 54, 508044, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 13, 54, 508089, tzinfo=<UTC>)\}, \{'id': 4, 'first_name': 'William', 'last_name': ' Shakespeare', 'email': 'william@book.com', 'notes': 'no value', 'created_at': datetime.datetime(2018, 12, 10, 22, 15, 1, 27856, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 15, 1, 27928, tzinfo=<UTC>)\}]>\
\
In [30]: secondbook = Book.objects.get(id = 2)\
\
In [31]: secondbook.authors.add(5)\
\
In [32]: secondbook.authors.all().values()\
Out[32]: <QuerySet [\{'id': 2, 'first_name': 'Emily', 'last_name': 'Dickinson', 'email': 'emily@book.com', 'notes': 'no value', 'created_at': datetime.datetime(2018, 12, 10, 22, 12, 45, 698866, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 12, 45, 698909, tzinfo=<UTC>)\}, \{'id': 1, 'first_name': 'Jane', 'last_name': 'Austin', 'email': 'jane@book.com', 'notes': 'no value', 'created_at': datetime.datetime(2018, 12, 10, 22, 12, 1, 910232, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 12, 1, 910275, tzinfo=<UTC>)\}, \{'id': 3, 'first_name': 'Fyodor', 'last_name': 'Do', 'email': 'fyodor@book.com', 'notes': 'no value', 'created_at': datetime.datetime(2018, 12, 10, 22, 13, 54, 508044, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 13, 54, 508089, tzinfo=<UTC>)\}, \{'id': 4, 'first_name': 'William', 'last_name': ' Shakespeare', 'email': 'william@book.com', 'notes': 'no value', 'created_at': datetime.datetime(2018, 12, 10, 22, 15, 1, 27856, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 15, 1, 27928, tzinfo=<UTC>)\}, \{'id': 5, 'first_name': 'Lau', 'last_name': 'Tzu', 'email': 'lau@book.com', 'notes': 'no value', 'created_at': datetime.datetime(2018, 12, 10, 22, 15, 33, 121823, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 15, 33, 121865, tzinfo=<UTC>)\}]>\
\
In [33]: author3 = Author.objects.get(id = 3)\
\
In [34]: author3.books.all().values()\
Out[34]: <QuerySet [\{'id': 1, 'name': 'C #', 'desc': 'terrible book', 'created_at': datetime.datetime(2018, 12, 10, 22, 8, 32, 501279, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 19, 58, 882873, tzinfo=<UTC>)\}, \{'id': 2, 'name': 'Java', 'desc': 'good book', 'created_at': datetime.datetime(2018, 12, 10, 22, 8, 56, 376415, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 8, 56, 376482, tzinfo=<UTC>)\}, \{'id': 3, 'name': 'Python', 'desc': 'great book', 'created_at': datetime.datetime(2018, 12, 10, 22, 9, 25, 248595, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 9, 25, 248663, tzinfo=<UTC>)\}, \{'id': 4, 'name': 'PHP', 'desc': 'obsolete book', 'created_at': datetime.datetime(2018, 12, 10, 22, 9, 51, 66207, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 9, 51, 66262, tzinfo=<UTC>)\}]>\
\
In [35]: fifthbook = Book.objects.get(id = 5)\
\
In [36]: fithbook.authors.all().values()\
---------------------------------------------------------------------------\
NameError                                 Traceback (most recent call last)\
<ipython-input-36-0947afabe7c5> in <module>\
----> 1 fithbook.authors.all().values()\
\
NameError: name 'fithbook' is not defined\
\
In [37]: fifthbook.authors.all().values()\
Out[37]: <QuerySet [\{'id': 4, 'first_name': 'William', 'last_name': ' Shakespeare', 'email': 'william@book.com', 'notes': 'no value', 'created_at': datetime.datetime(2018, 12, 10, 22, 15, 1, 27856, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 22, 15, 1, 27928, tzinfo=<UTC>)\}]>\
\
In [38]:     exit()\
(djangoPy3Env) Chis-MacBook-Air:Author_Book chinguyen$ cd ..\
(djangoPy3Env) Chis-MacBook-Air:django_orm chinguyen$ django-admin startproject Like_Book\
(djangoPy3Env) Chis-MacBook-Air:django_orm chinguyen$ cd Like_Book\
(djangoPy3Env) Chis-MacBook-Air:Like_Book chinguyen$ mkdir apps\
(djangoPy3Env) Chis-MacBook-Air:Like_Book chinguyen$ cd apps\
(djangoPy3Env) Chis-MacBook-Air:apps chinguyen$ django-admin startapp like_app\
(djangoPy3Env) Chis-MacBook-Air:apps chinguyen$ cd ..\
(djangoPy3Env) Chis-MacBook-Air:Like_Book chinguyen$ python manage.py runserver\
Performing system checks...\
\
System check identified no issues (0 silenced).\
\
You have 13 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\
Run 'python manage.py migrate' to apply them.\
\
December 10, 2018 - 23:04:17\
Django version 1.10, using settings 'Like_Book.settings'\
Starting development server at http://127.0.0.1:8000/\
Quit the server with CONTROL-C.\
[10/Dec/2018 23:04:37] "GET / HTTP/1.1" 200 1767\
Performing system checks...\
\
System check identified no issues (0 silenced).\
\
You have 13 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\
Run 'python manage.py migrate' to apply them.\
\
December 10, 2018 - 23:05:09\
Django version 1.10, using settings 'Like_Book.settings'\
Starting development server at http://127.0.0.1:8000/\
Quit the server with CONTROL-C.\
Performing system checks...\
\
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x1028c9400>\
Traceback (most recent call last):\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/utils/autoreload.py", line 226, in wrapper\
    fn(*args, **kwargs)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 121, ininner_run\
    self.check(display_num_errors=True)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/core/management/base.py", line 385, in check\
    include_deployment_checks=include_deployment_checks,\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/core/management/base.py", line 372, in _run_checks\
    return checks.run_checks(**kwargs)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/core/checks/registry.py", line 81, in run_checks\
    new_errors = check(app_configs=app_configs)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config\
    return check_resolver(resolver)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver\
    for pattern in resolver.url_patterns:\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/utils/functional.py", line 35, in __get__\
    res = instance.__dict__[self.name] = self.func(instance)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/urls/resolvers.py", line 310, in url_patterns\
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/utils/functional.py", line 35, in __get__\
    res = instance.__dict__[self.name] = self.func(instance)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/urls/resolvers.py", line 303, in urlconf_module\
    return import_module(self.urlconf_name)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/importlib/__init__.py", line 127, in import_module\
    return _bootstrap._gcd_import(name[level:], package, level)\
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import\
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load\
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked\
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked\
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module\
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/django/django_orm/Like_Book/Like_Book/urls.py", line 20, in <module>\
    url(r'^',include('apps.like_app.urls')),\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/conf/urls/__init__.py", line 50, in include\
    urlconf_module = import_module(urlconf_module)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/importlib/__init__.py", line 127, in import_module\
    return _bootstrap._gcd_import(name[level:], package, level)\
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import\
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load\
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked\
ModuleNotFoundError: No module named 'apps.like_app.urls'\
Performing system checks...\
\
System check identified no issues (0 silenced).\
\
You have 13 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\
Run 'python manage.py migrate' to apply them.\
\
December 10, 2018 - 23:08:20\
Django version 1.10, using settings 'Like_Book.settings'\
Starting development server at http://127.0.0.1:8000/\
Quit the server with CONTROL-C.\
Performing system checks...\
\
System check identified no issues (0 silenced).\
\
You have 13 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\
Run 'python manage.py migrate' to apply them.\
\
December 10, 2018 - 23:08:35\
Django version 1.10, using settings 'Like_Book.settings'\
Starting development server at http://127.0.0.1:8000/\
Quit the server with CONTROL-C.\
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10c58dd08>\
Traceback (most recent call last):\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/utils/autoreload.py", line 226, in wrapper\
    fn(*args, **kwargs)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 113, ininner_run\
    autoreload.raise_last_exception()\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception\
    six.reraise(*_exception)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/utils/six.py", line 685, in reraise\
    raise value.with_traceback(tb)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/utils/autoreload.py", line 226, in wrapper\
    fn(*args, **kwargs)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/__init__.py", line 27, in setup\
    apps.populate(settings.INSTALLED_APPS)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/apps/registry.py", line 108, in populate\
    app_config.import_models(all_models)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/apps/config.py", line 199, in import_models\
    self.models_module = import_module(models_module_name)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/importlib/__init__.py", line 127, in import_module\
    return _bootstrap._gcd_import(name[level:], package, level)\
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import\
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load\
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked\
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked\
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module\
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/django/django_orm/Like_Book/apps/like_app/models.py", line 3, in <module>\
    class User(models.Model):\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/django/django_orm/Like_Book/apps/like_app/models.py", line 7, in User\
    created_at = models.DateTimeField(auto_add_now = True)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 1164, in __init__\
    super(DateField, self).__init__(verbose_name, name, **kwargs)\
TypeError: __init__() got an unexpected keyword argument 'auto_add_now'\
^C(djangoPy3Env) Chis-MacBook-Air:Like_Book chinguyen$ python manage.py makemigrations\
Traceback (most recent call last):\
  File "manage.py", line 22, in <module>\
    execute_from_command_line(sys.argv)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line\
    utility.execute()\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/core/management/__init__.py", line 341, in execute\
    django.setup()\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/__init__.py", line 27, in setup\
    apps.populate(settings.INSTALLED_APPS)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/apps/registry.py", line 108, in populate\
    app_config.import_models(all_models)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/apps/config.py", line 199, in import_models\
    self.models_module = import_module(models_module_name)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/importlib/__init__.py", line 127, in import_module\
    return _bootstrap._gcd_import(name[level:], package, level)\
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import\
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load\
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked\
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked\
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module\
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/django/django_orm/Like_Book/apps/like_app/models.py", line 10, in <module>\
    class Book(models.Model):\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/django/django_orm/Like_Book/apps/like_app/models.py", line 14, in Book\
    liked_by = models.ManytoManyField(User,related_name = "liked_books")\
AttributeError: module 'django.db.models' has no attribute 'ManytoManyField'\
(djangoPy3Env) Chis-MacBook-Air:Like_Book chinguyen$ python manage.py makemigrations\
Traceback (most recent call last):\
  File "manage.py", line 22, in <module>\
    execute_from_command_line(sys.argv)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line\
    utility.execute()\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/core/management/__init__.py", line 341, in execute\
    django.setup()\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/__init__.py", line 27, in setup\
    apps.populate(settings.INSTALLED_APPS)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/apps/registry.py", line 108, in populate\
    app_config.import_models(all_models)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/apps/config.py", line 199, in import_models\
    self.models_module = import_module(models_module_name)\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/importlib/__init__.py", line 127, in import_module\
    return _bootstrap._gcd_import(name[level:], package, level)\
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import\
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load\
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked\
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked\
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module\
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/django/django_orm/Like_Book/apps/like_app/models.py", line 10, in <module>\
    class Book(models.Model):\
  File "/Users/chinguyen/1CODINGDOJO/python_stack/django/django_orm/Like_Book/apps/like_app/models.py", line 14, in Book\
    liked_by = models.ManytoManyField(User,related_name = "liked_books")\
AttributeError: module 'django.db.models' has no attribute 'ManytoManyField'\
(djangoPy3Env) Chis-MacBook-Air:Like_Book chinguyen$ python manage.py makemigrations\
Migrations for 'like_app':\
  apps/like_app/migrations/0001_initial.py:\
    - Create model Book\
    - Create model User\
    - Add field liked_by to book\
    - Add field uploaded_by to book\
(djangoPy3Env) Chis-MacBook-Air:Like_Book chinguyen$ python manage.py migrate\
Operations to perform:\
  Apply all migrations: admin, auth, contenttypes, like_app, sessions\
Running migrations:\
  Rendering model states... DONE\
  Applying contenttypes.0001_initial... OK\
  Applying auth.0001_initial... OK\
  Applying admin.0001_initial... OK\
  Applying admin.0002_logentry_remove_auto_add... OK\
  Applying contenttypes.0002_remove_content_type_name... OK\
  Applying auth.0002_alter_permission_name_max_length... OK\
  Applying auth.0003_alter_user_email_max_length... OK\
  Applying auth.0004_alter_user_username_opts... OK\
  Applying auth.0005_alter_user_last_login_null... OK\
  Applying auth.0006_require_contenttypes_0002... OK\
  Applying auth.0007_alter_validators_add_error_messages... OK\
  Applying auth.0008_alter_user_username_max_length... OK\
  Applying like_app.0001_initial... OK\
  Applying sessions.0001_initial... OK\
(djangoPy3Env) Chis-MacBook-Air:Like_Book chinguyen$ python manage.py shell\
Python 3.7.1 (default, Nov  6 2018, 18:45:35)\
Type 'copyright', 'credits' or 'license' for more information\
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.\
\
In [1]: from apps.like_app.models import *\
\
In [2]: User.objects.create(first_name = "Chi", last_name = "Nguyen", email = "chi@ee.com")\
Out[2]: <User: User object>\
\
In [3]: User.objects.create(first_name = "Danil", last_name = "Zakirov", email = "danil@ee.com")\
Out[3]: <User: User object>\
\
In [4]: User.objects.create(first_name = "Jessica", last_name ="Gee", email = "jess@ee.com")\
Out[4]: <User: User object>\
\
In [5]: book1= Book.objects.create(title = "book1", desc = "nice book")\
---------------------------------------------------------------------------\
IntegrityError                            Traceback (most recent call last)\
~/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/db/backends/utils.py in execute(self, sql, params)\
     63             else:\
---> 64                 return self.cursor.execute(sql, params)\
     65\
\
~/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py in execute(self, query, params)\
    336         query = self.convert_query(query)\
--> 337         return Database.Cursor.execute(self, query, params)\
    338\
\
IntegrityError: NOT NULL constraint failed: like_app_book.uploaded_by_id\
\
The above exception was the direct cause of the following exception:\
\
IntegrityError                            Traceback (most recent call last)\
<ipython-input-5-d98c1e305cb0> in <module>\
----> 1 book1= Book.objects.create(title = "book1", desc = "nice book")\
\
~/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/db/models/manager.py in manager_method(self, *args, **kwargs)\
     83         def create_method(name, method):\
     84             def manager_method(self, *args, **kwargs):\
---> 85                 return getattr(self.get_queryset(), name)(*args, **kwargs)\
     86             manager_method.__name__ = method.__name__\
     87             manager_method.__doc__ = method.__doc__\
\
~/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/db/models/query.py in create(self, **kwargs)\
    397         obj = self.model(**kwargs)\
    398         self._for_write = True\
--> 399         obj.save(force_insert=True, using=self.db)\
    400         return obj\
    401\
\
~/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/db/models/base.py in save(self, force_insert, force_update, using, update_fields)\
    794\
    795         self.save_base(using=using, force_insert=force_insert,\
--> 796                        force_update=force_update, update_fields=update_fields)\
    797     save.alters_data = True\
    798\
\
~/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/db/models/base.py in save_base(self, raw, force_insert, force_update, using, update_fields)\
    822             if not raw:\
    823                 self._save_parents(cls, using, update_fields)\
--> 824             updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)\
    825         # Store the database on which the object was saved\
    826         self._state.db = using\
\
~/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/db/models/base.py in _save_table(self, raw, cls, force_insert, force_update, using, update_fields)\
    906\
    907             update_pk = bool(meta.has_auto_field and not pk_set)\
--> 908             result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)\
    909             if update_pk:\
    910                 setattr(self, meta.pk.attname, result)\
\
~/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/db/models/base.py in _do_insert(self, manager, using, fields, update_pk, raw)\
    945         """\
    946         return manager._insert([self], fields=fields, return_id=update_pk,\
--> 947                                using=using, raw=raw)\
    948\
    949     def delete(self, using=None, keep_parents=False):\
\
~/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/db/models/manager.py in manager_method(self, *args, **kwargs)\
     83         def create_method(name, method):\
     84             def manager_method(self, *args, **kwargs):\
---> 85                 return getattr(self.get_queryset(), name)(*args, **kwargs)\
     86             manager_method.__name__ = method.__name__\
     87             manager_method.__doc__ = method.__doc__\
\
~/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/db/models/query.py in _insert(self, objs, fields, return_id, raw, using)\
   1041         query = sql.InsertQuery(self.model)\
   1042         query.insert_values(fields, objs, raw=raw)\
-> 1043         return query.get_compiler(using=using).execute_sql(return_id)\
   1044     _insert.alters_data = True\
   1045     _insert.queryset_only = False\
\
~/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/db/models/sql/compiler.py in execute_sql(self, return_id)\
   1052         with self.connection.cursor() as cursor:\
   1053             for sql, params in self.as_sql():\
-> 1054                 cursor.execute(sql, params)\
   1055             if not (return_id and cursor):\
   1056                 return\
\
~/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/db/backends/utils.py in execute(self, sql, params)\
     77         start = time()\
     78         try:\
---> 79             return super(CursorDebugWrapper, self).execute(sql, params)\
     80         finally:\
     81             stop = time()\
\
~/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/db/backends/utils.py in execute(self, sql, params)\
     62                 return self.cursor.execute(sql)\
     63             else:\
---> 64                 return self.cursor.execute(sql, params)\
     65\
     66     def executemany(self, sql, param_list):\
\
~/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/db/utils.py in __exit__(self, exc_type, exc_value, traceback)\
     92                 if dj_exc_type not in (DataError, IntegrityError):\
     93                     self.wrapper.errors_occurred = True\
---> 94                 six.reraise(dj_exc_type, dj_exc_value, traceback)\
     95\
     96     def __call__(self, func):\
\
~/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/utils/six.py in reraise(tp, value, tb)\
    683             value = tp()\
    684         if value.__traceback__ is not tb:\
--> 685             raise value.with_traceback(tb)\
    686         raise value\
    687\
\
~/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/db/backends/utils.py in execute(self, sql, params)\
     62                 return self.cursor.execute(sql)\
     63             else:\
---> 64                 return self.cursor.execute(sql, params)\
     65\
     66     def executemany(self, sql, param_list):\
\
~/1CODINGDOJO/python_stack/my_environments/djangoPy3Env/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py in execute(self, query, params)\
    335             return Database.Cursor.execute(self, query)\
    336         query = self.convert_query(query)\
--> 337         return Database.Cursor.execute(self, query, params)\
    338\
    339     def executemany(self, query, param_list):\
\
IntegrityError: NOT NULL constraint failed: like_app_book.uploaded_by_id\
\
In [6]: user1 = User.objects.get(id = 2)\
\
In [7]: book1 = Book.objects.create(title = "C #", desc = "ok book", uploaded_by = user1)\
\
In [8]: book1.__dict__\
Out[8]:\
\{'_state': <django.db.models.base.ModelState at 0x103fd2358>,\
 'id': 1,\
 'title': 'C #',\
 'desc': 'ok book',\
 'uploaded_by_id': 2,\
 '_uploaded_by_cache': <User: User object>,\
 'created_at': datetime.datetime(2018, 12, 10, 23, 36, 28, 310190, tzinfo=<UTC>),\
 'updated_at': datetime.datetime(2018, 12, 10, 23, 36, 28, 310232, tzinfo=<UTC>)\}\
\
In [9]: book2 = Book.objects.create(title = "Java", desc = "great book", uploaded_ by = user1)\
  File "<ipython-input-9-2b32e62cff7e>", line 1\
    book2 = Book.objects.create(title = "Java", desc = "great book", uploaded_ by = user1)\
                                                                                ^\
SyntaxError: invalid syntax\
\
\
In [10]: book2 = Book.objects.create(title = "Java", desc = "great book", uploaded_ by = user1)\
  File "<ipython-input-10-2b32e62cff7e>", line 1\
    book2 = Book.objects.create(title = "Java", desc = "great book", uploaded_ by = user1)\
                                                                                ^\
SyntaxError: invalid syntax\
\
\
In [11]: book2 = Book.objects.create(title = "Java", desc = "great book", uploaded_by = user1)\
\
In [12]: user2 = User.objects.get(id =2)\
\
In [13]: book3 = Book.objects.create(title = "Python", desc = "awesome book", uploaded_by = use2)\
---------------------------------------------------------------------------\
NameError                                 Traceback (most recent call last)\
<ipython-input-13-a4b73f69d77c> in <module>\
----> 1 book3 = Book.objects.create(title = "Python", desc = "awesome book", uploaded_by = use2)\
\
NameError: name 'use2' is not defined\
\
In [14]: user2\
Out[14]: <User: User object>\
\
In [15]: user2.__dict__\
Out[15]:\
\{'_state': <django.db.models.base.ModelState at 0x10406e780>,\
 'id': 2,\
 'first_name': 'Danil',\
 'last_name': 'Zakirov',\
 'email': 'danil@ee.com',\
 'created_at': datetime.datetime(2018, 12, 10, 23, 30, 6, 472363, tzinfo=<UTC>),\
 'updated_at': datetime.datetime(2018, 12, 10, 23, 30, 6, 472416, tzinfo=<UTC>)\}\
\
In [16]: book3 = Book.objects.create(title = "Python", desc = "awesome book", uploaded_by = user2)\
\
In [17]: book4 =Book.objects.create(title = "Go", desc = "best book", uploaded_by = user2)\
\
In [18]: user3 = User.objects.get(id = 3)\
\
In [19]: user3\
Out[19]: <User: User object>\
\
In [20]: book5 = Book.objects.create(title = "His Purchased Wife", desc = "another great book", uploaded_by = use3)\
---------------------------------------------------------------------------\
NameError                                 Traceback (most recent call last)\
<ipython-input-20-ade5e4b0b8b6> in <module>\
----> 1 book5 = Book.objects.create(title = "His Purchased Wife", desc = "another great book", uploaded_by = use3)\
\
NameError: name 'use3' is not defined\
\
In [21]: book5 = Book.objects.create(title = "His Purchased Wife", desc = "another great book", uploaded_by = user3)\
\
In [22]: book6 = Book.objects.create(title = "Good to Great", desc = "another great book", uploaded_by = user3)\
\
In [23]: user1.liked_books.add(1)\
\
In [24]: user1.like_books.all().values()\
---------------------------------------------------------------------------\
AttributeError                            Traceback (most recent call last)\
<ipython-input-24-0a63b29f27ef> in <module>\
----> 1 user1.like_books.all().values()\
\
AttributeError: 'User' object has no attribute 'like_books'\
\
In [25]: user1.liked_books.all().values()\
Out[25]: <QuerySet [\{'id': 1, 'title': 'C #', 'desc': 'ok book', 'uploaded_by_id': 2, 'created_at': datetime.datetime(2018, 12, 10, 23, 36, 28, 310190, tzinfo=<UTC>),'updated_at': datetime.datetime(2018, 12, 10, 23, 36, 28, 310232, tzinfo=<UTC>)\}]>\
\
In [26]: user1.liked_books.add(6)\
\
In [27]: user1.liked_books.all().values()\
Out[27]: <QuerySet [\{'id': 1, 'title': 'C #', 'desc': 'ok book', 'uploaded_by_id': 2, 'created_at': datetime.datetime(2018, 12, 10, 23, 36, 28, 310190, tzinfo=<UTC>),'updated_at': datetime.datetime(2018, 12, 10, 23, 36, 28, 310232, tzinfo=<UTC>)\}, \{'id': 6, 'title': 'Good to Great', 'desc': 'another great book', 'uploaded_by_id': 3, 'created_at': datetime.datetime(2018, 12, 10, 23, 43, 51, 15389, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 23, 43, 51, 15452, tzinfo=<UTC>)\}]>\
\
In [28]: user2.liked_books.add(1,3)\
\
In [29]: user2.liked_books.all().values()\
Out[29]: <QuerySet [\{'id': 1, 'title': 'C #', 'desc': 'ok book', 'uploaded_by_id': 2, 'created_at': datetime.datetime(2018, 12, 10, 23, 36, 28, 310190, tzinfo=<UTC>),'updated_at': datetime.datetime(2018, 12, 10, 23, 36, 28, 310232, tzinfo=<UTC>)\}, \{'id': 6, 'title': 'Good to Great', 'desc': 'another great book', 'uploaded_by_id': 3, 'created_at': datetime.datetime(2018, 12, 10, 23, 43, 51, 15389, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 23, 43, 51, 15452, tzinfo=<UTC>)\}, \{'id': 3, 'title': 'Python', 'desc': 'awesome book', 'uploaded_by_id': 2, 'created_at': datetime.datetime(2018, 12, 10, 23, 40, 51, 994441, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 23, 40, 51, 994484, tzinfo=<UTC>)\}]>\
\
In [30]: user3.liked_books.add(1,2,3,4,5,6)\
\
In [31]: user3.liked_books.all().values()\
Out[31]: <QuerySet [\{'id': 1, 'title': 'C #', 'desc': 'ok book', 'uploaded_by_id': 2, 'created_at': datetime.datetime(2018, 12, 10, 23, 36, 28, 310190, tzinfo=<UTC>),'updated_at': datetime.datetime(2018, 12, 10, 23, 36, 28, 310232, tzinfo=<UTC>)\}, \{'id': 2, 'title': 'Java', 'desc': 'great book', 'uploaded_by_id': 2, 'created_at': datetime.datetime(2018, 12, 10, 23, 37, 29, 663315, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 23, 37, 29, 663359, tzinfo=<UTC>)\}, \{'id': 3, 'title':'Python', 'desc': 'awesome book', 'uploaded_by_id': 2, 'created_at': datetime.datetime(2018, 12, 10, 23, 40, 51, 994441, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 23, 40, 51, 994484, tzinfo=<UTC>)\}, \{'id': 4, 'title': 'Go', 'desc': 'best book', 'uploaded_by_id': 2, 'created_at': datetime.datetime(2018, 12, 10, 23, 41, 32, 983434, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 23, 41, 32, 983476, tzinfo=<UTC>)\}, \{'id': 5, 'title': 'His Purchased Wife', 'desc': 'another great book', 'uploaded_by_id': 3, 'created_at': datetime.datetime(2018, 12, 10, 23, 43, 16, 584479, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 23, 43, 16, 584522, tzinfo=<UTC>)\}, \{'id': 6, 'title': 'Good to Great', 'desc': 'another great book', 'uploaded_by_id': 3, 'created_at': datetime.datetime(2018, 12, 10, 23, 43, 51, 15389, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 23, 43, 51, 15452, tzinfo=<UTC>)\}]>\
\
In [32]: User.objects.all().liked_books\
---------------------------------------------------------------------------\
AttributeError                            Traceback (most recent call last)\
<ipython-input-32-48c59e3f8c71> in <module>\
----> 1 User.objects.all().liked_books\
\
AttributeError: 'QuerySet' object has no attribute 'liked_books'\
\
In [33]: book1.liked_by.all().values()\
Out[33]: <QuerySet [\{'id': 2, 'first_name': 'Danil', 'last_name': 'Zakirov', 'email': 'danil@ee.com', 'created_at': datetime.datetime(2018, 12, 10, 23, 30, 6, 472363,tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 23, 30, 6, 472416, tzinfo=<UTC>)\}, \{'id': 3, 'first_name': 'Jessica', 'last_name': 'Gee', 'email': 'jess@ee.com', 'created_at': datetime.datetime(2018, 12, 10, 23, 30, 39, 633761, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 23, 30, 39, 633814, tzinfo=<UTC>)\}]>\
\
In [34]: book1.uploaded_by.all().values()\
---------------------------------------------------------------------------\
AttributeError                            Traceback (most recent call last)\
<ipython-input-34-e788d91d5770> in <module>\
----> 1 book1.uploaded_by.all().values()\
\
AttributeError: 'User' object has no attribute 'all'\
\
In [35]: book1.uploaded_by.all()\
---------------------------------------------------------------------------\
AttributeError                            Traceback (most recent call last)\
<ipython-input-35-4dae467f0382> in <module>\
----> 1 book1.uploaded_by.all()\
\
AttributeError: 'User' object has no attribute 'all'\
\
In [36]: book1.uploaded_by.values()\
---------------------------------------------------------------------------\
AttributeError                            Traceback (most recent call last)\
<ipython-input-36-dc20a98d934c> in <module>\
----> 1 book1.uploaded_by.values()\
\
AttributeError: 'User' object has no attribute 'values'\
\
In [37]: book1.books_uploaded.all().values()\
---------------------------------------------------------------------------\
AttributeError                            Traceback (most recent call last)\
<ipython-input-37-8fdb385cd2e4> in <module>\
----> 1 book1.books_uploaded.all().values()\
\
AttributeError: 'Book' object has no attribute 'books_uploaded'\
\
In [38]: Book.objects.first().uploaded_by\
Out[38]: <User: User object>\
\
In [39]: Book.objects.first().uploaded_by.values()\
---------------------------------------------------------------------------\
AttributeError                            Traceback (most recent call last)\
<ipython-input-39-fd44c19f4f4f> in <module>\
----> 1 Book.objects.first().uploaded_by.values()\
\
AttributeError: 'User' object has no attribute 'values'\
\
In [40]: User.__dict__\
Out[40]:\
mappingproxy(\{'__module__': 'apps.like_app.models',\
              '__doc__': 'User(id, first_name, last_name, email, created_at, updated_at)',\
              '_meta': <Options for User>,\
              'DoesNotExist': apps.like_app.models.DoesNotExist,\
              'MultipleObjectsReturned': apps.like_app.models.MultipleObjectsReturned,\
              'first_name': <django.db.models.query_utils.DeferredAttribute at 0x102aa8390>,\
              'last_name': <django.db.models.query_utils.DeferredAttribute at 0x102aa83c8>,\
              'email': <django.db.models.query_utils.DeferredAttribute at 0x102aa8470>,\
              'created_at': <django.db.models.query_utils.DeferredAttribute at 0x102ab1a58>,\
              'get_next_by_created_at': <function django.utils.functional.curry.<locals>._curried(*moreargs, **morekwargs)>,\
              'get_previous_by_created_at': <function django.utils.functional.curry.<locals>._curried(*moreargs, **morekwargs)>,\
              'updated_at': <django.db.models.query_utils.DeferredAttribute at 0x102ab1ba8>,\
              'get_next_by_updated_at': <function django.utils.functional.curry.<locals>._curried(*moreargs, **morekwargs)>,\
              'get_previous_by_updated_at': <function django.utils.functional.curry.<locals>._curried(*moreargs, **morekwargs)>,\
              'id': <django.db.models.query_utils.DeferredAttribute at 0x102ab1c50>,\
              'objects': <django.db.models.manager.ManagerDescriptor at 0x102ab1c88>,\
              'books_uploaded': <django.db.models.fields.related_descriptors.ReverseManyToOneDescriptor at 0x102ac3e48>,\
              'liked_books': <django.db.models.fields.related_descriptors.ManyToManyDescriptor at 0x102ac3e80>\})\
\
In [41]: User.objects.first().books_uploaded.values()\
Out[41]: <QuerySet []>\
\
In [42]: User.objects.get(id=2).liked_books.values()\
Out[42]: <QuerySet [\{'id': 1, 'title': 'C #', 'desc': 'ok book', 'uploaded_by_id': 2, 'created_at': datetime.datetime(2018, 12, 10, 23, 36, 28, 310190, tzinfo=<UTC>),'updated_at': datetime.datetime(2018, 12, 10, 23, 36, 28, 310232, tzinfo=<UTC>)\}, \{'id': 6, 'title': 'Good to Great', 'desc': 'another great book', 'uploaded_by_id': 3, 'created_at': datetime.datetime(2018, 12, 10, 23, 43, 51, 15389, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 23, 43, 51, 15452, tzinfo=<UTC>)\}, \{'id': 3, 'title': 'Python', 'desc': 'awesome book', 'uploaded_by_id': 2, 'created_at': datetime.datetime(2018, 12, 10, 23, 40, 51, 994441, tzinfo=<UTC>), 'updated_at': datetime.datetime(2018, 12, 10, 23, 40, 51, 994484, tzinfo=<UTC>)\}]>\
\
In [43]: Book.objects.get(id = 2).uploaded_by.values()\
---------------------------------------------------------------------------\
AttributeError                            Traceback (most recent call last)\
<ipython-input-43-8bcbb68718b9> in <module>\
----> 1 Book.objects.get(id = 2).uploaded_by.values()\
\
AttributeError: 'User' object has no attribute 'values'\
\
In [44]: book2 = Book.objects.get(id = 2)\
\
In [45]: book2.uploaded_by\
Out[45]: <User: User object> // To get the value from the User, need to get User\'92s attribute\
\
In [46]: book2.uploaded_by.values()\
\'97\'97\'97AttributeError: type object 'User' has no attribute 'values'\
\
>> In [48]: book2.uploaded_by.first_name\
Out[48]: 'Danil'\
}